-- Table IIID. Encounters Per Visit and Per Patient
-- Encounter counts, patient counts, visits, and encounters per visit by encounter type.
-- Visit = unique (PATID, ENC_TYPE, ADMIT_DATE, PROVIDERID). Supports DC 2.04.
-- Exceptions (avg enc/visit > 2.0 for IP/ED/EI) highlighted in blue.

WITH all_enc AS (
    SELECT PATID, ENC_TYPE, ADMIT_DATE::DATE AS ADMIT_DATE, PROVIDERID, ENCOUNTERID
    FROM {{ current_schema }}.ENCOUNTER
),
visits AS (
    SELECT ENC_TYPE, PATID, ADMIT_DATE, PROVIDERID,
           COUNT(DISTINCT ENCOUNTERID) AS ENC_PER_VISIT
    FROM all_enc
    GROUP BY ENC_TYPE, PATID, ADMIT_DATE, PROVIDERID
),
by_type AS (
    SELECT
        CASE WHEN ENC_TYPE IN ('AV','ED','EI','IC','IP','IS','OA','OS','TH') THEN ENC_TYPE
             ELSE 'Missing/NI/UN/OT' END AS ENC_TYPE_GRP,
        COUNT(DISTINCT ENCOUNTERID) AS ENCOUNTERS,
        COUNT(DISTINCT PATID) AS PATIENTS,
        SUM(CASE WHEN PROVIDERID IS NOT NULL THEN 1 ELSE 0 END) AS ENC_WITH_PROVIDERID
    FROM all_enc
    GROUP BY 1
),
visits_by_type AS (
    SELECT
        CASE WHEN ENC_TYPE IN ('AV','ED','EI','IC','IP','IS','OA','OS','TH') THEN ENC_TYPE
             ELSE 'Missing/NI/UN/OT' END AS ENC_TYPE_GRP,
        COUNT(*) AS VISITS,
        SUM(CASE WHEN PROVIDERID IS NOT NULL THEN ENC_PER_VISIT ELSE 0 END) AS ENC_W_PROV_TOTAL,
        SUM(CASE WHEN PROVIDERID IS NOT NULL THEN 1 ELSE 0 END) AS VISITS_WITH_PROVIDERID
    FROM visits
    GROUP BY 1
),
all_types AS (
    SELECT 'AV' AS ENC_TYPE, 1 AS ROW_ORDER UNION ALL
    SELECT 'ED', 2 UNION ALL
    SELECT 'EI', 3 UNION ALL
    SELECT 'IC', 4 UNION ALL
    SELECT 'IP', 5 UNION ALL
    SELECT 'IS', 6 UNION ALL
    SELECT 'OA', 7 UNION ALL
    SELECT 'OS', 8 UNION ALL
    SELECT 'TH', 9 UNION ALL
    SELECT 'Missing/NI/UN/OT', 10
)
SELECT
    t.ENC_TYPE,
    TO_VARCHAR(COALESCE(b.ENCOUNTERS, 0)) AS ENCOUNTERS,
    TO_VARCHAR(COALESCE(b.PATIENTS, 0)) AS PATIENTS,
    TO_VARCHAR(ROUND(COALESCE(b.ENCOUNTERS, 0) * 1.0 / NULLIF(b.PATIENTS, 0), 2)) AS ENC_PER_PATIENT,
    TO_VARCHAR(COALESCE(b.ENC_WITH_PROVIDERID, 0)) AS ENC_WITH_PROVIDERID,
    TO_VARCHAR(COALESCE(v.VISITS, 0)) AS VISITS,
    TO_VARCHAR(ROUND(COALESCE(b.ENCOUNTERS, 0) * 1.0 / NULLIF(v.VISITS, 0), 2)) AS ENC_WITH_PROVIDERID_PER_VISIT,
    'ENC_L3_N' AS SOURCE_TABLE
FROM all_types t
LEFT JOIN by_type b ON b.ENC_TYPE_GRP = t.ENC_TYPE
LEFT JOIN visits_by_type v ON v.ENC_TYPE_GRP = t.ENC_TYPE

UNION ALL

SELECT
    'Total',
    TO_VARCHAR(SUM(ENCOUNTERS)),
    TO_VARCHAR(COUNT(DISTINCT PATID)),
    TO_VARCHAR(ROUND(SUM(ENCOUNTERS) * 1.0 / NULLIF(COUNT(DISTINCT PATID), 0), 2)),
    TO_VARCHAR(SUM(ENC_WITH_PROVIDERID)),
    TO_VARCHAR((SELECT COUNT(*) FROM visits)),
    TO_VARCHAR(ROUND(SUM(ENCOUNTERS) * 1.0 / NULLIF((SELECT COUNT(*) FROM visits), 0), 2)),
    'ENC_L3_N'
FROM by_type

ORDER BY
    CASE ENC_TYPE
        WHEN 'AV' THEN 1 WHEN 'ED' THEN 2 WHEN 'EI' THEN 3 WHEN 'IC' THEN 4
        WHEN 'IP' THEN 5 WHEN 'IS' THEN 6 WHEN 'OA' THEN 7 WHEN 'OS' THEN 8
        WHEN 'TH' THEN 9 WHEN 'Missing/NI/UN/OT' THEN 10 ELSE 11 END
