-- Table IIIG. Monthly Record Volume Outliers, Selected Domains
-- Outliers for DC 2.08: months where RECORDS = 0 OR Difference Ratio ≤ -7.0.
-- Difference Ratio = (RECORDS - AVG_PREV_12MO) / STDDEV_PREV_12MO.
-- Months excluded if AVG_PREV_12MO < 500 or STDDEV_PREV_12MO = 0.
-- Evaluation window: months 13-60 before report_month. Exceptions highlighted in blue.

WITH eval_months AS (
    SELECT
        DATE_TRUNC('month', DATEADD(month, -(seq + 13), TO_DATE('{{ report_month }}'))) AS MONTH_START
    FROM (
        SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS seq
        FROM TABLE(GENERATOR(ROWCOUNT => 48))
    )
    WHERE DATE_TRUNC('month', DATEADD(month, -(seq + 13), TO_DATE('{{ report_month }}'))) >= TO_DATE('{{ start_date }}')
),
eval_window AS (
    SELECT TO_VARCHAR(MIN(MONTH_START), 'YYYY-MM-DD') || ' to ' ||
           TO_VARCHAR(MAX(MONTH_START), 'YYYY-MM-DD') AS EVAL_WINDOW_STR
    FROM eval_months
),
all_months AS (
    SELECT DATE_TRUNC('month', DATEADD(month, -seq, TO_DATE('{{ report_month }}'))) AS MONTH_START
    FROM (
        SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS seq
        FROM TABLE(GENERATOR(ROWCOUNT => 60))
    )
    WHERE DATE_TRUNC('month', DATEADD(month, -seq, TO_DATE('{{ report_month }}'))) >= TO_DATE('{{ start_date }}')
),
enc_monthly AS (
    SELECT DATE_TRUNC('month', ADMIT_DATE) AS MONTH_START, ENC_TYPE, COUNT(*) AS CNT
    FROM {{ current_schema }}.ENCOUNTER
    WHERE ENC_TYPE IN ('AV','TH','OA','ED','EI','IP')
    GROUP BY 1, 2
),
diag_monthly AS (
    SELECT DATE_TRUNC('month', ADMIT_DATE) AS MONTH_START, ENC_TYPE, COUNT(*) AS CNT
    FROM {{ current_schema }}.DIAGNOSIS
    WHERE ENC_TYPE IN ('AV','TH','OA','ED','EI','IP')
    GROUP BY 1, 2
),
px_monthly AS (
    SELECT DATE_TRUNC('month', PX_DATE) AS MONTH_START, ENC_TYPE, COUNT(*) AS CNT
    FROM {{ current_schema }}.PROCEDURES
    WHERE ENC_TYPE IN ('AV','TH','OA','ED','EI','IP')
    GROUP BY 1, 2
),
vital_monthly AS (
    SELECT DATE_TRUNC('month', MEASURE_DATE) AS MONTH_START, COUNT(*) AS CNT
    FROM {{ current_schema }}.VITAL GROUP BY 1
),
rx_monthly AS (
    SELECT DATE_TRUNC('month', RX_ORDER_DATE) AS MONTH_START, COUNT(*) AS CNT
    FROM {{ current_schema }}.PRESCRIBING GROUP BY 1
),
lab_monthly AS (
    SELECT DATE_TRUNC('month', RESULT_DATE) AS MONTH_START, COUNT(*) AS CNT
    FROM {{ current_schema }}.LAB_RESULT_CM GROUP BY 1
),
medadmin_monthly AS (
    SELECT DATE_TRUNC('month', MEDADMIN_START_DATE) AS MONTH_START, COUNT(*) AS CNT
    FROM {{ current_schema }}.MED_ADMIN GROUP BY 1
),
enc_type_months AS (
    SELECT t.MONTH_START, et.ENC_TYPE, COALESCE(e.CNT, 0) AS RECORDS
    FROM all_months t
    CROSS JOIN (SELECT 'AV' AS ENC_TYPE UNION ALL SELECT 'TH' UNION ALL SELECT 'OA'
                UNION ALL SELECT 'ED' UNION ALL SELECT 'EI' UNION ALL SELECT 'IP') et
    LEFT JOIN enc_monthly e ON e.MONTH_START = t.MONTH_START AND e.ENC_TYPE = et.ENC_TYPE
),
diag_type_months AS (
    SELECT t.MONTH_START, et.ENC_TYPE, COALESCE(e.CNT, 0) AS RECORDS
    FROM all_months t
    CROSS JOIN (SELECT 'AV' AS ENC_TYPE UNION ALL SELECT 'TH' UNION ALL SELECT 'OA'
                UNION ALL SELECT 'ED' UNION ALL SELECT 'EI' UNION ALL SELECT 'IP') et
    LEFT JOIN diag_monthly e ON e.MONTH_START = t.MONTH_START AND e.ENC_TYPE = et.ENC_TYPE
),
px_type_months AS (
    SELECT t.MONTH_START, et.ENC_TYPE, COALESCE(e.CNT, 0) AS RECORDS
    FROM all_months t
    CROSS JOIN (SELECT 'AV' AS ENC_TYPE UNION ALL SELECT 'TH' UNION ALL SELECT 'OA'
                UNION ALL SELECT 'ED' UNION ALL SELECT 'EI' UNION ALL SELECT 'IP') et
    LEFT JOIN px_monthly e ON e.MONTH_START = t.MONTH_START AND e.ENC_TYPE = et.ENC_TYPE
),
vital_all_months AS (
    SELECT t.MONTH_START, COALESCE(v.CNT, 0) AS RECORDS
    FROM all_months t LEFT JOIN vital_monthly v ON v.MONTH_START = t.MONTH_START
),
rx_all_months AS (
    SELECT t.MONTH_START, COALESCE(r.CNT, 0) AS RECORDS
    FROM all_months t LEFT JOIN rx_monthly r ON r.MONTH_START = t.MONTH_START
),
lab_all_months AS (
    SELECT t.MONTH_START, COALESCE(l.CNT, 0) AS RECORDS
    FROM all_months t LEFT JOIN lab_monthly l ON l.MONTH_START = t.MONTH_START
),
medadmin_all_months AS (
    SELECT t.MONTH_START, COALESCE(m.CNT, 0) AS RECORDS
    FROM all_months t LEFT JOIN medadmin_monthly m ON m.MONTH_START = t.MONTH_START
),
with_stats AS (
    SELECT 'ENCOUNTER' AS TABLE_NAME, ENC_TYPE, MONTH_START, RECORDS,
           AVG(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING) AS AVG_12,
           STDDEV(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING) AS STD_12
    FROM enc_type_months
    UNION ALL
    SELECT 'DIAGNOSIS', ENC_TYPE, MONTH_START, RECORDS,
           AVG(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM diag_type_months
    UNION ALL
    SELECT 'PROCEDURES', ENC_TYPE, MONTH_START, RECORDS,
           AVG(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (PARTITION BY ENC_TYPE ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM px_type_months
    UNION ALL
    SELECT 'VITAL', '', MONTH_START, RECORDS,
           AVG(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM vital_all_months
    UNION ALL
    SELECT 'PRESCRIBING', '', MONTH_START, RECORDS,
           AVG(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM rx_all_months
    UNION ALL
    SELECT 'LAB_RESULT_CM', '', MONTH_START, RECORDS,
           AVG(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM lab_all_months
    UNION ALL
    SELECT 'MED_ADMIN', '', MONTH_START, RECORDS,
           AVG(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING),
           STDDEV(RECORDS) OVER (ORDER BY MONTH_START ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING)
    FROM medadmin_all_months
),
outliers AS (
    SELECT ws.TABLE_NAME, ew.EVAL_WINDOW_STR AS EVAL_WINDOW, ws.ENC_TYPE,
           ws.MONTH_START AS EXCEPTION_MONTH,
           ws.RECORDS,
           ROUND(ws.AVG_12, 0) AS AVG_PREV_12MO,
           ROUND(ws.STD_12, 2) AS STDDEV_PREV_12MO,
           ROUND((ws.RECORDS - ws.AVG_12) / NULLIF(ws.STD_12, 0), 2) AS DIFF_RATIO
    FROM with_stats ws, eval_window ew
    JOIN eval_months em ON em.MONTH_START = ws.MONTH_START
    WHERE ws.AVG_12 >= 500
      AND ws.STD_12 > 0
      AND (ws.RECORDS = 0 OR (ws.RECORDS - ws.AVG_12) / NULLIF(ws.STD_12, 0) <= -7.0)
)
SELECT TABLE_NAME, EVAL_WINDOW, ENC_TYPE,
       TO_VARCHAR(EXCEPTION_MONTH, 'YYYY-MM') AS EXCEPTION_MONTH,
       TO_VARCHAR(RECORDS) AS RECORDS,
       TO_VARCHAR(AVG_PREV_12MO) AS AVG_PREV_12MO,
       TO_VARCHAR(STDDEV_PREV_12MO) AS STDDEV_PREV_12MO,
       TO_VARCHAR(DIFF_RATIO) AS DIFF_RATIO,
       'ENC_L3_N; DIA_L3_N; PRO_L3_N; VIT_L3_N; PRES_L3_N; LAB_L3_N; MEDA_L3_N' AS SOURCE_TABLE
FROM outliers

UNION ALL

SELECT 'No Data Table contains a Data Check Exception', '', '', '', '', '', '', '', ''
WHERE NOT EXISTS (SELECT 1 FROM outliers)

ORDER BY TABLE_NAME, ENC_TYPE, EXCEPTION_MONTH
