-- Table IVA. Diagnosis Records Per Encounter and Per Patient, Overall and by Encounter Type
-- Supports DC 3.01 (avg diagnoses with known DX_TYPE per encounter below threshold).
-- Threshold: >= 1.0 for AV, IP, ED, EI, TH encounters. Exceptions highlighted in blue.

WITH enc_counts AS (
    SELECT
        CASE WHEN ENC_TYPE IN ('AV','ED','EI','IC','IP','IS','OA','OS','TH') THEN ENC_TYPE
             ELSE 'Missing/NI/UN/OT' END AS ENC_TYPE_GRP,
        COUNT(*) AS ENC_RECORDS
    FROM {{ current_schema }}.ENCOUNTER
    WHERE ADMIT_DATE >= TO_DATE('{{ start_date }}') AND ADMIT_DATE <= TO_DATE('{{ end_date }}')
    GROUP BY 1
),
dx_counts AS (
    SELECT
        CASE WHEN ENC_TYPE IN ('AV','ED','EI','IC','IP','IS','OA','OS','TH') THEN ENC_TYPE
             ELSE 'Missing/NI/UN/OT' END AS ENC_TYPE_GRP,
        COUNT(*) AS DX_RECORDS,
        SUM(CASE WHEN DX_TYPE NOT IN ('NI','UN','OT') THEN 1 ELSE 0 END) AS DX_RECORDS_KNOWN_DXTYPE
    FROM {{ current_schema }}.DIAGNOSIS
    WHERE ADMIT_DATE >= TO_DATE('{{ start_date }}') AND ADMIT_DATE <= TO_DATE('{{ end_date }}')
    GROUP BY 1
),
all_types AS (
    SELECT 'AV' AS ENC_TYPE, 1 AS ROW_ORDER UNION ALL
    SELECT 'ED', 2 UNION ALL SELECT 'EI', 3 UNION ALL SELECT 'IC', 4 UNION ALL
    SELECT 'IP', 5 UNION ALL SELECT 'IS', 6 UNION ALL SELECT 'OA', 7 UNION ALL
    SELECT 'OS', 8 UNION ALL SELECT 'TH', 9 UNION ALL SELECT 'Missing/NI/UN/OT', 10
)
SELECT
    t.ENC_TYPE,
    TO_VARCHAR(COALESCE(d.DX_RECORDS, 0)) AS DX_RECORDS,
    TO_VARCHAR(COALESCE(d.DX_RECORDS_KNOWN_DXTYPE, 0)) AS DX_RECORDS_KNOWN_DXTYPE,
    TO_VARCHAR(COALESCE(e.ENC_RECORDS, 0)) AS ENC_RECORDS,
    TO_VARCHAR(ROUND(COALESCE(d.DX_RECORDS, 0) * 1.0 / NULLIF(e.ENC_RECORDS, 0), 2)) AS DX_PER_ENC,
    TO_VARCHAR(ROUND(COALESCE(d.DX_RECORDS_KNOWN_DXTYPE, 0) * 1.0 / NULLIF(e.ENC_RECORDS, 0), 2)) AS DX_KNOWN_TYPE_PER_ENC
FROM all_types t
LEFT JOIN enc_counts e ON e.ENC_TYPE_GRP = t.ENC_TYPE
LEFT JOIN dx_counts d ON d.ENC_TYPE_GRP = t.ENC_TYPE

UNION ALL

SELECT 'Total',
    TO_VARCHAR(SUM(d.DX_RECORDS)),
    TO_VARCHAR(SUM(d.DX_RECORDS_KNOWN_DXTYPE)),
    TO_VARCHAR(SUM(e.ENC_RECORDS)),
    TO_VARCHAR(ROUND(SUM(d.DX_RECORDS) * 1.0 / NULLIF(SUM(e.ENC_RECORDS), 0), 2)),
    TO_VARCHAR(ROUND(SUM(d.DX_RECORDS_KNOWN_DXTYPE) * 1.0 / NULLIF(SUM(e.ENC_RECORDS), 0), 2))
FROM enc_counts e
LEFT JOIN dx_counts d ON d.ENC_TYPE_GRP = e.ENC_TYPE_GRP

ORDER BY
    CASE ENC_TYPE WHEN 'AV' THEN 1 WHEN 'ED' THEN 2 WHEN 'EI' THEN 3 WHEN 'IC' THEN 4
    WHEN 'IP' THEN 5 WHEN 'IS' THEN 6 WHEN 'OA' THEN 7 WHEN 'OS' THEN 8
    WHEN 'TH' THEN 9 WHEN 'Missing/NI/UN/OT' THEN 10 ELSE 11 END
