-- Table ID. Records, Refresh Dates, Patients, Encounters, and Date Ranges by Table
-- Characterized data is restricted to start_date lookback except for DEMOGRAPHIC, DEATH_CAUSE,
-- HASH_TOKEN, LAB_HISTORY, LDS_ADDRESS_HISTORY, and PROVIDER. Supports DC 1.18.

WITH harvest AS (
    SELECT * FROM {{ current_schema }}.HARVEST LIMIT 1
)
SELECT
    TABLE_NAME   AS "Table",
    ALL_RECORDS  AS "ALL DATA__Records",
    REFRESH_DATE AS "ALL DATA__Refresh Date",
    CHAR_RECORDS AS "CHARACTERIZED DATA__Records",
    CHAR_PATIENTS AS "CHARACTERIZED DATA__Patients",
    CHAR_ENCOUNTERS AS "CHARACTERIZED DATA__Encounters",
    FIELD_NAME   AS "CHARACTERIZED DATA RANGE__Field Name",
    P5_DATE      AS "CHARACTERIZED DATA RANGE__5th Percentile",
    P95_DATE     AS "CHARACTERIZED DATA RANGE__95th Percentile"
FROM (

    SELECT 'DEMOGRAPHIC' AS TABLE_NAME,
           TO_VARCHAR(COUNT(*))                                                                              AS ALL_RECORDS,
           TO_VARCHAR(MAX(h.REFRESH_DEMOGRAPHIC_DATE))                                                      AS REFRESH_DATE,
           TO_VARCHAR(COUNT(*))                                                                              AS CHAR_RECORDS,
           TO_VARCHAR(COUNT(DISTINCT PATID))                                                                 AS CHAR_PATIENTS,
           ''                                                                                                AS CHAR_ENCOUNTERS,
           'BIRTH_DATE'                                                                                      AS FIELD_NAME,
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', BIRTH_DATE)), DATE '1970-01-01')) AS P5_DATE,
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', BIRTH_DATE)), DATE '1970-01-01')) AS P95_DATE,
           1 AS ROW_ORDER
    FROM {{ current_schema }}.DEMOGRAPHIC, harvest h UNION ALL

    SELECT 'ENROLLMENT',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_ENROLLMENT_DATE)),
           TO_VARCHAR(SUM(CASE WHEN ENR_START_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ENR_START_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'ENR_START_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ENR_START_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ENR_START_DATE)), DATE '1970-01-01')),
           2
    FROM {{ current_schema }}.ENROLLMENT, harvest h UNION ALL

    SELECT 'ENCOUNTER',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_ENCOUNTER_DATE)),
           TO_VARCHAR(SUM(CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'ADMIT_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           3
    FROM {{ current_schema }}.ENCOUNTER, harvest h UNION ALL

    SELECT 'DIAGNOSIS',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_DIAGNOSIS_DATE)),
           TO_VARCHAR(SUM(CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'ADMIT_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           4
    FROM {{ current_schema }}.DIAGNOSIS, harvest h UNION ALL

    SELECT 'PROCEDURES',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_PROCEDURES_DATE)),
           TO_VARCHAR(SUM(CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN ADMIT_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'ADMIT_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', ADMIT_DATE)), DATE '1970-01-01')),
           5
    FROM {{ current_schema }}.PROCEDURES, harvest h UNION ALL

    SELECT 'DEATH',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_DEATH_DATE)),
           TO_VARCHAR(SUM(CASE WHEN DEATH_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN DEATH_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'DEATH_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', DEATH_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', DEATH_DATE)), DATE '1970-01-01')),
           6
    FROM {{ current_schema }}.DEATH, harvest h UNION ALL

    SELECT 'VITAL',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_VITAL_DATE)),
           TO_VARCHAR(SUM(CASE WHEN MEASURE_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN MEASURE_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN MEASURE_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'MEASURE_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', MEASURE_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', MEASURE_DATE)), DATE '1970-01-01')),
           7
    FROM {{ current_schema }}.VITAL, harvest h UNION ALL

    SELECT 'LAB_RESULT_CM',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_LAB_RESULT_CM_DATE)),
           TO_VARCHAR(SUM(CASE WHEN RESULT_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN RESULT_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN RESULT_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'RESULT_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', RESULT_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', RESULT_DATE)), DATE '1970-01-01')),
           8
    FROM {{ current_schema }}.LAB_RESULT_CM, harvest h UNION ALL

    SELECT 'PRESCRIBING',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_PRESCRIBING_DATE)),
           TO_VARCHAR(SUM(CASE WHEN RX_ORDER_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN RX_ORDER_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN RX_ORDER_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'RX_ORDER_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', RX_ORDER_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', RX_ORDER_DATE)), DATE '1970-01-01')),
           9
    FROM {{ current_schema }}.PRESCRIBING, harvest h UNION ALL

    SELECT 'DISPENSING',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_DISPENSING_DATE)),
           TO_VARCHAR(SUM(CASE WHEN DISPENSE_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN DISPENSE_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'DISPENSE_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', DISPENSE_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', DISPENSE_DATE)), DATE '1970-01-01')),
           10
    FROM {{ current_schema }}.DISPENSING, harvest h UNION ALL

    SELECT 'CONDITION',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_CONDITION_DATE)),
           TO_VARCHAR(SUM(CASE WHEN REPORT_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN REPORT_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'REPORT_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', REPORT_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', REPORT_DATE)), DATE '1970-01-01')),
           11
    FROM {{ current_schema }}.CONDITION, harvest h UNION ALL

    SELECT 'DEATH_CAUSE',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_DEATH_DATE)),
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(COUNT(DISTINCT PATID)),
           '', '', '', '',
           12
    FROM {{ current_schema }}.DEATH_CAUSE, harvest h UNION ALL

    SELECT 'PRO_CM',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_PRO_CM_DATE)),
           TO_VARCHAR(SUM(CASE WHEN PRO_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN PRO_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'PRO_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', PRO_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', PRO_DATE)), DATE '1970-01-01')),
           13
    FROM {{ current_schema }}.PRO_CM, harvest h UNION ALL

    SELECT 'PROVIDER',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_PROVIDER_DATE)),
           TO_VARCHAR(COUNT(*)),
           '', '', '', '', '',
           14
    FROM {{ current_schema }}.PROVIDER, harvest h UNION ALL

    SELECT 'MED_ADMIN',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_MED_ADMIN_DATE)),
           TO_VARCHAR(SUM(CASE WHEN MEDADMIN_START_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN MEDADMIN_START_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN MEDADMIN_START_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'MEDADMIN_START_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', MEDADMIN_START_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', MEDADMIN_START_DATE)), DATE '1970-01-01')),
           15
    FROM {{ current_schema }}.MED_ADMIN, harvest h UNION ALL

    SELECT 'OBS_CLIN',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_OBS_CLIN_DATE)),
           TO_VARCHAR(SUM(CASE WHEN OBSCLIN_START_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN OBSCLIN_START_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN OBSCLIN_START_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'OBSCLIN_START_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', OBSCLIN_START_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', OBSCLIN_START_DATE)), DATE '1970-01-01')),
           16
    FROM {{ current_schema }}.OBS_CLIN, harvest h UNION ALL

    SELECT 'OBS_GEN',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_OBS_GEN_DATE)),
           TO_VARCHAR(SUM(CASE WHEN OBSGEN_START_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN OBSGEN_START_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN OBSGEN_START_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'OBSGEN_START_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', OBSGEN_START_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', OBSGEN_START_DATE)), DATE '1970-01-01')),
           17
    FROM {{ current_schema }}.OBS_GEN, harvest h UNION ALL

    SELECT 'PCORNET_TRIAL',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_PCORNET_TRIAL_DATE)),
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(COUNT(DISTINCT PATID)),
           '', '', '', '',
           18
    FROM {{ current_schema }}.PCORNET_TRIAL, harvest h UNION ALL

    SELECT 'HASH_TOKEN',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_HASH_TOKEN_DATE)),
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(COUNT(DISTINCT PATID)),
           '', '', '', '',
           19
    FROM {{ current_schema }}.HASH_TOKEN, harvest h UNION ALL

    SELECT 'LDS_ADDRESS_HISTORY',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_LDS_ADDRESS_HX_DATE)),
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(COUNT(DISTINCT PATID)),
           '', '', '', '',
           20
    FROM {{ current_schema }}.LDS_ADDRESS_HISTORY, harvest h UNION ALL

    SELECT 'IMMUNIZATION',
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(MAX(h.REFRESH_IMMUNIZATION_DATE)),
           TO_VARCHAR(SUM(CASE WHEN VX_RECORD_DATE >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN VX_RECORD_DATE >= TO_DATE('{{ start_date }}') THEN PATID END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN VX_RECORD_DATE >= TO_DATE('{{ start_date }}') THEN ENCOUNTERID END)),
           'VX_RECORD_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', VX_RECORD_DATE)), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', VX_RECORD_DATE)), DATE '1970-01-01')),
           21
    FROM {{ current_schema }}.IMMUNIZATION, harvest h UNION ALL

    SELECT 'LAB_HISTORY',
           TO_VARCHAR(COUNT(*)),
           NULL,
           TO_VARCHAR(COUNT(*)),
           '', '', '', '', '',
           22
    FROM {{ current_schema }}.LAB_HISTORY, harvest h UNION ALL

    SELECT 'EXTERNAL_MEDS',
           TO_VARCHAR(COUNT(*)),
           NULL,
           TO_VARCHAR(SUM(CASE WHEN TO_DATE(TO_VARCHAR(EXT_RECORD_DATE)) >= TO_DATE('{{ start_date }}') THEN 1 ELSE 0 END)),
           TO_VARCHAR(COUNT(DISTINCT CASE WHEN TO_DATE(TO_VARCHAR(EXT_RECORD_DATE)) >= TO_DATE('{{ start_date }}') THEN PATID END)),
           '',
           'EXT_RECORD_DATE',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', TO_DATE(TO_VARCHAR(EXT_RECORD_DATE)))), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', TO_DATE(TO_VARCHAR(EXT_RECORD_DATE)))), DATE '1970-01-01')),
           23
    FROM {{ current_schema }}.EXTERNAL_MEDS, harvest h UNION ALL

    SELECT 'PAT_RELATIONSHIP',
           TO_VARCHAR(COUNT(*)),
           null,
           TO_VARCHAR(COUNT(*)),
           TO_VARCHAR(COUNT(DISTINCT PATID_1)),
           '',
           'RELATIONSHIP_START',
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', TO_DATE(TO_VARCHAR(RELATIONSHIP_START)))), DATE '1970-01-01')),
           TO_VARCHAR(DATEADD(DAY, PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY DATEDIFF(DAY, DATE '1970-01-01', TO_DATE(TO_VARCHAR(RELATIONSHIP_START)))), DATE '1970-01-01')),
           24
    FROM {{ current_schema }}.PAT_RELATIONSHIP, harvest h

) subq
ORDER BY ROW_ORDER