CREATE TABLE IF NOT EXISTS DQ_NETWORKS (
    NETWORK_ID   VARCHAR(36)   NOT NULL PRIMARY KEY,
    NETWORK_NAME VARCHAR(255)  NOT NULL,
    DESCRIPTION  VARCHAR(1000) DEFAULT '',
    CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DQ_SITES (
    SITE_ID       VARCHAR(36)   NOT NULL PRIMARY KEY,
    NETWORK_ID    VARCHAR(36)   NOT NULL,
    SITE_NAME     VARCHAR(255)  NOT NULL,
    DATABASE_NAME VARCHAR(255)  NOT NULL,
    CDM_SCHEMA    VARCHAR(255)  DEFAULT '',
    DESCRIPTION   VARCHAR(1000) DEFAULT '',
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DQ_RUNS (
    RUN_ID         VARCHAR(36)  NOT NULL PRIMARY KEY,
    NETWORK_ID     VARCHAR(36),
    SITE_ID        VARCHAR(36),
    CDM_SCHEMA     VARCHAR(255),
    CUTOFF_DATE    DATE,
    LOOKBACK_YEARS INTEGER      DEFAULT 10,
    TRIGGERED_BY   VARCHAR(255),
    STATUS         VARCHAR(50),
    STARTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT   TIMESTAMP_NTZ,
    SESSION_ID     VARCHAR(36),
    PREV_SCHEMA    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DQ_CHECK_RESULTS (
    RESULT_ID     VARCHAR(36)   NOT NULL PRIMARY KEY,
    RUN_ID        VARCHAR(36)   NOT NULL,
    CHECK_ID      VARCHAR(255),
    CHECK_NAME    VARCHAR(255),
    SQL_EXECUTED  VARCHAR(8000),
    STATUS        VARCHAR(50),
    TOTAL_COUNT   INTEGER       DEFAULT 0,
    ERROR_MESSAGE VARCHAR(2000),
    EXECUTED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NETWORK_ID    VARCHAR(36),
    SITE_ID       VARCHAR(36),
    DURATION_MS   INTEGER       DEFAULT 0,
    RESULT_DATA   VARIANT
)
