-- Table IIC. Non-Permissible Missing Values
-- Lists all required CDM fields that contain NULL or empty-string values (non-permissible missing).
-- Supports DC 1.07. Permissible "informationally missing" tokens (NI/UN/OT) are NOT flagged.
-- Exceptions highlighted in red and must be corrected.
-- Parameters: {{ current_schema }}

WITH violations AS (
{% set required_fields = [
    ('DEMOGRAPHIC', 'PATID'),
    ('DEMOGRAPHIC', 'BIRTH_DATE'),
    ('DEMOGRAPHIC', 'SEX'),
    ('DEMOGRAPHIC', 'HISPANIC'),
    ('DEMOGRAPHIC', 'RACE'),
    ('ENROLLMENT', 'PATID'),
    ('ENROLLMENT', 'ENR_START_DATE'),
    ('ENROLLMENT', 'ENR_BASIS'),
    ('ENCOUNTER', 'ENCOUNTERID'),
    ('ENCOUNTER', 'PATID'),
    ('ENCOUNTER', 'ADMIT_DATE'),
    ('ENCOUNTER', 'ENC_TYPE'),
    ('DIAGNOSIS', 'DIAGNOSISID'),
    ('DIAGNOSIS', 'PATID'),
    ('DIAGNOSIS', 'ENCOUNTERID'),
    ('DIAGNOSIS', 'DX'),
    ('DIAGNOSIS', 'DX_TYPE'),
    ('PROCEDURES', 'PROCEDURESID'),
    ('PROCEDURES', 'PATID'),
    ('PROCEDURES', 'ENCOUNTERID'),
    ('PROCEDURES', 'PX'),
    ('PROCEDURES', 'PX_TYPE'),
    ('VITAL', 'VITALID'),
    ('VITAL', 'PATID'),
    ('VITAL', 'MEASURE_DATE'),
    ('VITAL', 'VITAL_SOURCE'),
    ('DEATH', 'PATID'),
    ('DEATH', 'DEATH_SOURCE'),
    ('DEATH_CAUSE', 'PATID'),
    ('DEATH_CAUSE', 'DEATH_CAUSE'),
    ('DEATH_CAUSE', 'DEATH_CAUSE_CODE'),
    ('DEATH_CAUSE', 'DEATH_CAUSE_TYPE'),
    ('DEATH_CAUSE', 'DEATH_CAUSE_SOURCE'),
    ('CONDITION', 'CONDITIONID'),
    ('CONDITION', 'PATID'),
    ('CONDITION', 'CONDITION'),
    ('CONDITION', 'CONDITION_SOURCE'),
    ('PRO_CM', 'PRO_CM_ID'),
    ('PRO_CM', 'PATID'),
    ('DISPENSING', 'DISPENSINGID'),
    ('DISPENSING', 'PATID'),
    ('DISPENSING', 'DISPENSE_DATE'),
    ('DISPENSING', 'NDC'),
    ('PRESCRIBING', 'PRESCRIBINGID'),
    ('PRESCRIBING', 'PATID'),
    ('PRESCRIBING', 'RXNORM_CUI'),
    ('MED_ADMIN', 'MEDADMINID'),
    ('MED_ADMIN', 'PATID'),
    ('MED_ADMIN', 'ENCOUNTERID'),
    ('LAB_RESULT_CM', 'LAB_RESULT_CM_ID'),
    ('LAB_RESULT_CM', 'PATID'),
    ('OBS_CLIN', 'OBSCLINID'),
    ('OBS_CLIN', 'PATID'),
    ('OBS_GEN', 'OBSGENID'),
    ('OBS_GEN', 'PATID'),
    ('IMMUNIZATION', 'IMMUNIZATIONID'),
    ('IMMUNIZATION', 'PATID'),
    ('IMMUNIZATION', 'VX_CODE'),
    ('IMMUNIZATION', 'VX_CODE_TYPE'),
    ('LAB_HISTORY', 'LABHISTORYID'),
    ('HASH_TOKEN', 'PATID'),
    ('HASH_TOKEN', 'TOKEN_ENCRYPTION_KEY'),
    ('LDS_ADDRESS_HISTORY', 'ADDRESSID'),
    ('LDS_ADDRESS_HISTORY', 'PATID'),
    ('PCORNET_TRIAL', 'PATID'),
    ('PCORNET_TRIAL', 'TRIALID'),
    ('PCORNET_TRIAL', 'PARTICIPANTID'),
    ('PROVIDER', 'PROVIDERID'),
    ('EXTERNAL_MEDS', 'PATID'),
    ('EXTERNAL_MEDS', 'EXTMEDID'),
    ('PAT_RELATIONSHIP', 'PATID_1'),
    ('PAT_RELATIONSHIP', 'PATID_2'),
    ('PAT_RELATIONSHIP', 'RELATIONSHIP_TYPE'),
    ('HARVEST', 'NETWORKID'),
    ('HARVEST', 'DATAMARTID'),
] %}
{% for tbl, fld in required_fields %}
    {% if not loop.first %}UNION ALL {% endif %}SELECT '{{ tbl }}' AS T, '{{ fld }}' AS F,
        SUM(CASE WHEN {{ fld }} IS NULL OR TRIM({{ fld }}::STRING) = '' THEN 1 ELSE 0 END) AS N
    FROM {{ current_schema }}.{{ tbl }}
    HAVING SUM(CASE WHEN {{ fld }} IS NULL OR TRIM({{ fld }}::STRING) = '' THEN 1 ELSE 0 END) > 0
{% endfor %}
)
SELECT T AS "Table",
       F AS "Field",
       TO_VARCHAR(N) AS "Number of records with missing values"
FROM violations
ORDER BY "Table", "Field"
